services:
  - type: web
    name: blaze-business-os
    runtime: node
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: node server-static.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: blaze-super-secret-key-2024
      - key: CLERK_PUBLISHABLE_KEY
        value: pk_test_YWJvdmUtd2hpcHBldC0zNi5jbGVyay5hY2NvdW50cy5kZXYk
      - key: CLERK_SECRET_KEY
        value: sk_test_k61iDDorYAqa5TSxzaw1xcHQz3PH4blo1XSSp6ztqJ
      - key: SYSTEME_API_KEY
        value: gutxuny6z7abcijjhr16yqazqltx43z5gqcl8jpo12mibokr31js1hfc0ed8i8k2